# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mht_code', models.BigIntegerField(blank=True, db_column='MHT_CODE', null=True)),
                ('biome', models.TextField(blank=True, db_column='BIOME', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('short_biome', models.TextField(blank=True, db_column='SHORT_BIOME', null=True)),
            ],
            options={
                'db_table': 'biomes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.BigIntegerField(blank=True, db_column='CLASS_ID', null=True)),
                ('class_field', models.TextField(blank=True, db_column='CLASS', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColumnTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField(blank=True, db_column='TABLE_NAME', null=True)),
                ('column_name', models.TextField(blank=True, db_column='COLUMN_NAME', null=True)),
                ('display_name', models.TextField(blank=True, db_column='DISPLAY_NAME', null=True)),
                ('_id', models.BigIntegerField(blank=True, db_column='ID', null=True)),
            ],
            options={
                'db_table': 'column_translation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommonNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name_id', models.BigIntegerField(blank=True, db_column='COMMON_NAME_ID', null=True)),
                ('common_name', models.TextField(blank=True, db_column='COMMON_NAME', null=True)),
                ('species_id', models.BigIntegerField(blank=True, db_column='SPECIES_ID', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'common_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConservationSts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conservation_status', models.BigIntegerField(blank=True, db_column='CONSERVATION_STATUS', null=True)),
                ('conservation_status_desc', models.TextField(blank=True, db_column='CONSERVATION_STATUS_DESC', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'conservation_sts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ecoregions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoregion_code', models.TextField(blank=True, db_column='ECOREGION_CODE', null=True)),
                ('ecoregion_name', models.TextField(blank=True, db_column='ECOREGION_NAME', null=True)),
                ('ecoregion_area', models.BigIntegerField(blank=True, db_column='ECOREGION_AREA', null=True)),
                ('global200_num', models.BigIntegerField(blank=True, db_column='GLOBAL200_NUM', null=True)),
                ('conservation_status', models.BigIntegerField(blank=True, db_column='CONSERVATION_STATUS', null=True)),
                ('analysis', models.TextField(blank=True, db_column='ANALYSIS', null=True)),
                ('realm_code', models.TextField(blank=True, db_column='REALM_CODE', null=True)),
                ('mht_code', models.BigIntegerField(blank=True, db_column='MHT_CODE', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('info_location', models.TextField(blank=True, db_column='INFO_LOCATION', null=True)),
                ('alternate_name', models.TextField(blank=True, db_column='ALTERNATE_NAME', null=True)),
            ],
            options={
                'db_table': 'ecoregions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EcoregionSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoregion_code', models.TextField(blank=True, db_column='ECOREGION_CODE', null=True)),
                ('species_id', models.BigIntegerField(blank=True, db_column='SPECIES_ID', null=True)),
                ('eco_endemic', models.TextField(blank=True, db_column='ECO_ENDEMIC', null=True)),
                ('deleted', models.TextField(blank=True, db_column='DELETED', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('introduced', models.TextField(blank=True, db_column='INTRODUCED', null=True)),
                ('_id', models.BigIntegerField(blank=True, db_column='ID', null=True)),
            ],
            options={
                'db_table': 'ecoregion_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.BigIntegerField(blank=True, db_column='FAMILY_ID', null=True)),
                ('family', models.TextField(blank=True, db_column='FAMILY', null=True)),
                ('order_id', models.BigIntegerField(blank=True, db_column='ORDER_ID', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'family',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genus_id', models.BigIntegerField(blank=True, db_column='GENUS_ID', null=True)),
                ('genus', models.TextField(blank=True, db_column='GENUS', null=True)),
                ('family_id', models.BigIntegerField(blank=True, db_column='FAMILY_ID', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'genus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Global200',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global200_num', models.BigIntegerField(blank=True, db_column='GLOBAL200_NUM', null=True)),
                ('global200_name', models.TextField(blank=True, db_column='GLOBAL200_NAME', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'global_200',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealmCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realm_code', models.TextField(blank=True, db_column='REALM_CODE', null=True)),
                ('realm', models.TextField(blank=True, db_column='REALM', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'realm_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedlistCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_list_category', models.TextField(blank=True, db_column='RED_LIST_CATEGORY', null=True)),
                ('red_list_cat_desc', models.TextField(blank=True, db_column='RED_LIST_CAT_DESC', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
            ],
            options={
                'db_table': 'redlist_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedlistSpecies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redlist_id', models.BigIntegerField(blank=True, db_column='REDLIST_ID', null=True)),
                ('genus', models.TextField(blank=True, db_column='GENUS', null=True)),
                ('species', models.TextField(blank=True, db_column='SPECIES', null=True)),
                ('red_list_category', models.TextField(blank=True, db_column='RED_LIST_CATEGORY', null=True)),
                ('rlscrit', models.TextField(blank=True, db_column='RLSCRIT', null=True)),
                ('wwf_species_id', models.TextField(blank=True, db_column='WWF_SPECIES_ID', null=True)),
            ],
            options={
                'db_table': 'redlist_species',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_id', models.BigIntegerField(blank=True, db_column='SPECIES_ID', null=True)),
                ('species', models.TextField(blank=True, db_column='SPECIES', null=True)),
                ('genus_id', models.BigIntegerField(blank=True, db_column='GENUS_ID', null=True)),
                ('mapped', models.TextField(blank=True, db_column='MAPPED', null=True)),
                ('deleted', models.TextField(blank=True, db_column='DELETED', null=True)),
                ('strict_endemism', models.TextField(blank=True, db_column='STRICT_ENDEMISM', null=True)),
                ('modified_by', models.TextField(blank=True, db_column='MODIFIED_BY', null=True)),
                ('date_modified', models.TextField(blank=True, db_column='DATE_MODIFIED', null=True)),
                ('created_by', models.TextField(blank=True, db_column='CREATED_BY', null=True)),
                ('date_created', models.TextField(blank=True, db_column='DATE_CREATED', null=True)),
                ('info_location', models.TextField(blank=True, db_column='INFO_LOCATION', null=True)),
            ],
            options={
                'db_table': 'species',
                'managed': False,
            },
        ),
    ]
